### ISSUE TITLE
Chicken door opening doesn't stop

### ISSUE THREAD

**Issue by doramelindatunde** [cornucopia-machines/ugly-duckling-firmware#177]
door opens too wide, then fails all the time

**Comment by lptr** [comment]
It's the "open" sensor, somehow it's not working properly. We could alternatively detect the motor stalling (=high current) at the top position.

**Comment by doramelindatunde** [comment]
Makes sense.

**Comment by lptr** [comment]
Looks to be working now after replacing the Reed relays with Hall sensors.
