### ISSUE TITLE
Establish new main line

### ISSUE THREAD

**Issue by doramelindatunde** [cornucopia-machines/ugly-duckling-firmware#37]
New main line should be dug into ground for protection, with 3 frost free points of serviceable access (house - _mains_, well - _neem_, hoop house - _cucumbers, tomatoes, planting bench, cooling, drains_). All other ducklings will be on solar power and as close to the bed as possible. We need a visszacsapószelep in drains to be sure that the neem/clean water do not mix.

**Comment by lptr** [comment]
This is done, right?

**Comment by doramelindatunde** [comment]
The drains part is not and the old pipeline still needs to be taken down. Also, all the gadgetst need to be put in the basement of the other house
